version: "3"

services:
  node:
    build:
      context: .
      dockerfile: Dockerfile    
    container_name: node
    restart: always
    env_file:
      - .env
    ports:
      - 3000:3000
    links:
      - redis
      - mongodb

  mongodb:
    image: mongo:latest
    container_name: mongodb
    hostname: mongodb
    restart: always
    ports:
      - 27017:27017
    volumes:
      - /data/mongodb:/data/db

  redis:
    image: redis:latest
    restart: always
    ports:
     - 6379:6379
